---
# setup repo if package is unavailable, using official SUSE NHC repo
- name: Install NHC OBS repo if enabled
  community.general.zypper_repository:
    repo: "{{ nhc_suse_repo }}"
    runrefresh: true
  when: nhc_suse_repo_enable

- name: Install NHC
  community.general.zypper:
    name: "{{ nhc_suse_package_name }}={{ nhc_version }}"
